"""Cleaning and quality filtering for Python source data.

The order that matters in a real pipeline:
    normalize -> license filter -> validity/quality filter -> dedup (dedup.py)

Each function here is pure and independently testable. None of this is "smart" —
data cleaning is mostly a stack of cheap, conservative heuristics that remove the
obviously-bad, because bad data hurts a small model disproportionately.
"""

from __future__ import annotations

import ast
import unicodedata

# Licenses we consider permissive enough to train on. In a real pipeline this is
# matched against repo metadata (e.g. GitHub's licensee output), not file text.
PERMISSIVE_LICENSES = frozenset(
    {"mit", "apache-2.0", "bsd-3-clause", "bsd-2-clause", "isc", "cc0-1.0", "unlicense", "psf"}
)


def normalize_text(src: str) -> str:
    """Canonicalize line endings, unicode form, and trailing whitespace.

    Deterministic normalization keeps the tokenizer from wasting vocab on trivial
    variants (\\r\\n vs \\n, NFC vs NFD) and makes dedup effective.
    """
    src = src.replace("\r\n", "\n").replace("\r", "\n")
    src = unicodedata.normalize("NFC", src)
    # strip trailing spaces per line; strip trailing blank lines; ensure final \n
    lines = [ln.rstrip() for ln in src.split("\n")]
    text = "\n".join(lines).strip("\n")
    return text + "\n" if text else ""


def is_valid_python(src: str) -> bool:
    """True iff the source parses as Python 3 (syntactically valid)."""
    try:
        ast.parse(src)
        return True
    except (SyntaxError, ValueError):  # ValueError covers e.g. null bytes
        return False


def is_permissive_license(license_id: str | None) -> bool:
    """True iff a (SPDX-ish) license id is on our permissive allow-list."""
    if not license_id:
        return False
    return license_id.strip().lower() in PERMISSIVE_LICENSES


def passes_quality(
    src: str,
    min_lines: int = 3,
    max_line_length: int = 1000,
    min_alpha_fraction: float = 0.15,
    max_avg_line_length: float = 120.0,
) -> bool:
    """Conservative quality gate to drop autogenerated/minified/garbage files.

    Heuristics (mirroring what large code corpora use):
      * too few lines -> trivial/snippet noise
      * an extremely long line -> minified or data blob
      * low alphabetic fraction -> base64/hex/data, not real code
      * very long average line -> generated/packed code
    """
    if not src.strip():
        return False
    lines = src.split("\n")
    if len(lines) < min_lines:
        return False
    if any(len(ln) > max_line_length for ln in lines):
        return False
    non_empty = [ln for ln in lines if ln.strip()]
    if non_empty:
        avg_len = sum(len(ln) for ln in non_empty) / len(non_empty)
        if avg_len > max_avg_line_length:
            return False
    alpha = sum(c.isalpha() for c in src)
    if alpha / max(len(src), 1) < min_alpha_fraction:
        return False
    return True


def clean_document(
    src: str,
    license_id: str | None = None,
    require_valid: bool = True,
    require_license: bool = False,
) -> str | None:
    """Run the full per-document gate. Returns cleaned text, or None if rejected."""
    if require_license and not is_permissive_license(license_id):
        return None
    text = normalize_text(src)
    if not passes_quality(text):
        return None
    if require_valid and not is_valid_python(text):
        return None
    return text
